### ISSUE TITLE
Crawl / manually curate / map Dataset resources into individual metadata records based off of schema

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info-resources#10]
Map [resource list](https://docs.google.com/spreadsheets/d/1FFyRhI5TeUb-B4t50HRZYF_XngRt_mfAIz82UQ3geFk/edit#gid=0) to Dataset schema.  Should also rely on [crawler.biothings.io](http://crawler.biothings.io/) to grab datasets from Figshare, Harvard Dataverse, etc.

**Comment by andrewsu** [comment]
List of generalist repositories hosting COVID data and code at this link https://datascience.nih.gov/news/nih-to-host-webinar-on-sharing-discovering-and-citing-covid-19-data-and-code-in-generalist-repositories-on-april-24. Sites included:

* vivli.org: https://vivli.org/how-to-share-your-research-on-the-vivli-covid-19-portal/
* Figshare: https://covid19.figshare.com/
* GitHub: https://github.com/github/covid-19-repo-data
* Dryad (no direct link)
* Zenodo: https://zenodo.org/communities/covid-19/?page=1&size=20
* Harvard Dataverse: https://projects.iq.harvard.edu/chinadatalab/resources-covid-19
* Mendeley Data: https://data.mendeley.com/research-data/elsevier-covid19

**Comment by flaneuse** [comment]
FYI the link to Harvard Dataverse is one dataverse from the China Data Lab, not all the dataverses.

crawler.biothings.io should be able to grab Figshare, Dataverse, and Zenodo if updated. 

current repo counts:
vivli: 0 studies (?)
figshare: 223
github: enormous list of repos containing data
dryad: a few
zenodo: 214
dataverse: 87
mendeley: 4

**Comment by andrewsu** [comment]
COVID-specific API links:

Figshare: https://covid19.figshare.com/api/institutions/857/items?types=&licenses=&orderBy=published_date&orderType=desc&limit=40&search=&categories=&itemTypes=

**Comment by flaneuse** [comment]
Figshare importation could be tackled with two approaches (or a hybrid of the two).

1. Some pages have [https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Ffigshare.com%2Farticles%2FData_on_the_COVID-19_outbreak_in_Romania%2F12045243](embedded schema.org json metadata) in a `<script type="application/ld+json">` tag.  So, using the API, we could get the URLs, scrape the ld+json data, add a couple of outbreak-resource-specific things, and upload.

BUT... [other records](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Ftandf.figshare.com%2Farticles%2FNovel_2019_Coronavirus_Structure_Mechanism_of_Action_Antiviral_drug_promises_and_rule_out_against_its_treatment%2F12154767) don't have this tag, meaning we need to pull the metadata some other way.

2. Pull all the data from their [API](https://covid19.figshare.com/api/institutions/857/items?types=&licenses=&orderBy=published_date&orderType=desc&limit=40&search=&categories=&itemTypes=) and map to schema.org properties (for instance `publishedDate` to `datePublished`).

Personally, approach 2 seems like more work, but if we're going to have to do it anyway for records without embedded metadata, we might as well do it for everything.

**Comment by flaneuse** [comment]
MVP developed w/ Zenodo crawler, Figshare parser. Closing and creating separate issues for other data sources as they arise
