### ISSUE TITLE
[DDE GUIDE ISSUE] - Funding Type wrong, funder incorrect

### ISSUE THREAD

**Issue by gtsueng** [SuLab/outbreak.info-resources#121]
In the JSON generated via the guide, the Funding `@type` is incorrect. It should be `Monetary Grant`, not`Organization`.  Additionally, the `funder` should be an object of type `Organization` with a `name` property instead of a direct string.

The issue with the funder name is expected to be one of the reasons why the guide does not allow for successful submissions.  This is a blocker which needs to be resolved ASAP.

**Comment by flaneuse** [comment]
Submission also fails for a .json generated by the guide which lacks the `funding` info: https://github.com/SuLab/outbreak.info-resources/blob/master/metadata/manual_additions/JHU.json
