### ISSUE TITLE
Find and incorporate suitable ontologies for Analysis techniques

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info-resources#14]

**Comment by gtsueng** [comment]
I'm not clear on what the heck this is.  If it's meant to refer to the mathematical models used for the analysis, I'd suggest MaMO https://www.ebi.ac.uk/ols/ontologies/mamo

**Comment by gtsueng** [comment]
Based on discussions, analysisTechniques will be the type of analysis run, while another field will capture the underlying intent/question/aim/purpose of the analysis. For the underlying intent/questoin/aim/purpose field, a Covid-19 specific controlled vocabulary should be used. The [COVID-19 surveillance ontology](https://bioportal.bioontology.org/ontologies/COVID19/?p=classes&conceptid=root) and the [Coronavirus Infectious Disease Ontology (CIDO)](http://bioportal.bioontology.org/ontologies/CIDO/?p=classes&conceptid=root) maybe good places to start

**Comment by gtsueng** [comment]
A more general topicCategory has been added to all outbreak schemas so that thematically related resources can be searched. The terms and for the keywords will likely be drawn from the Covid-19 primer
