### ISSUE TITLE
Find and incorporate suitable ontologies for MeasurementTechnique, VariableMeasured

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info-resources#15]
can build off of NIAID dataset schema: https://github.com/SuLab/niaid-data-portal/blob/master/schema/NIAID-Dataset-schema.yaml (see "vocabulary")

**Comment by gtsueng** [comment]
MeasurementTechnique ~ assay --> https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000070&viewMode=All&siblings=false

Measurement --> subset of https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001444&viewMode=All&siblings=false
