### ISSUE TITLE
Develop a controlled vocabulary and guidelines for tagging resources with biologically relevant information

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info-resources#16]
related to #14, #15 -- how do we want to classify these resources to help make them easier to find?

**Comment by gtsueng** [comment]
If we don't want to have to tag them ourselves, we could pull the MH (mesh terms) and OT (other terms) which have been curated by the folks at NCBI from the publication associated with the resource.

**Comment by flaneuse** [comment]
possibly supplement / align with https://covid19primer.com/ categories?

**Comment by flaneuse** [comment]
LitCovid topics: https://www.ncbi.nlm.nih.gov/research/coronavirus/docsum?filters=topics.Prevention. 
- GENERAL
- MECHANISM: Underlying cause(s) of covid-19 infections and transmission & possible drug mechanism of action
- TRANSMISSION: Characteristics and modes of covid-19 transmissions, such as human-to-human
- DIAGNOSIS: Disease assessment through symptoms, test results, and radiological features
- TREATMENT: Treatment strategies, therapeutic procedures, and vaccine development
- PREVENTION: Prevention, control, and management strategies
- CASE REPORT: Descriptions of specific patient cases
- FORECASTING: Modelling and estimating the trend of covid-19 spread

**Comment by flaneuse** [comment]
proposal at https://docs.google.com/spreadsheets/d/1eAYqX0Gq63iID-IYzfhlUO_ugjsdooSzNkJP4y6KFxc/edit#gid=2081989406
