### ISSUE TITLE
Define query terms to search for on Publication / Dataset sources that have searchable interfaces

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info-resources#18]
Figshare (Dataset source), Pubmed (Publication source), and others have searchable interfaces and/or APIs which allow us to more or less directly import the metadata about the individual resources, which will then be need to be mapped to our schema.

prelim list (plus variations with capitalization and hyphenation):
Severe acute respiratory syndrome coronavirus 2
COVID19
SARS-2
SARS-CoV2
SARS-CoV-2
HCoV-19
SARS2
2019-nCoV
COVID-19
COVID-19 virus
Wuhan coronavirus
Wuhan seafood market pneumonia virus
Human coronavirus 2019
novel coronavirus 2019
novel coronavirus **NOTE: need to be careful about this one, since this was also the original name for MERS**

**Comment by flaneuse** [comment]
Primarily taken from [NCBI Taxonomy ID: 2697049 synonyms](https://www.ncbi.nlm.nih.gov/taxonomy/2697049)

**Comment by gtsueng** [comment]
I've seen 'ARDS coronavirus' used early on.  Like 'novel coronavirus', it could capture some MERS stuff, but if an additional filter on the publication date is used, you should be able to restrict it to just sar-cov2.
