### ISSUE TITLE
Create Protocol .yaml schema

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info-resources#3]

**Comment by andrewsu** [comment]
Can we use https://bioschemas.org/profiles/LabProtocol/0.3-DRAFT-2019_06_14/ directly?

**Comment by gtsueng** [comment]
> 
> 
> Can we use https://bioschemas.org/profiles/LabProtocol/0.3-DRAFT-2019_06_14/ directly?

We could, but protocols from protocols.io and other sources don't necessarily include a purpose statement, but have a description. We can collapse chem/reagents and samples to materials which is used in protocols.io and is less restrictive than chem/reagents. We also want to be consistent in our use of isBasedOn, relatedTo, citedBy to link other types of resources such as datasets, publications, etc.

**Comment by andrewsu** [comment]
yeah, all good points.  I'm fine adapting as needed.  (For example, I think for our use case, annotating the actual reagents is of less importance than isBasedOn, relatedTo, citedBy...)

**Comment by kwende** [comment]
Notes for myself. Here is @gtsueng 's document on it: https://docs.google.com/spreadsheets/d/1BQAIT2Vw-I8SqWFArQP1dmj9gcv1lX7oNd-nTEOi9yY/edit#gid=978166538.

**Comment by gtsueng** [comment]
For any of the worksheets in the document, you should exclude/ignore any rows highlighted in red (considered, but didn't make the cut), and any columns right of "allowed values" (example resources from which the field was drawn).

**Comment by flaneuse** [comment]
From CViSB call today, consider how to distinguish medical protocols and medical and/or public health guidance from lab or analysis protocols.  Relevant schema.org schemas:
- [MedicalGuideline](https://schema.org/MedicalGuideline)
- [MedicalProcedure](https://schema.org/MedicalProcedure)
- [DiagnosticProcedure](https://schema.org/DiagnosticProcedure)
- [TherapeuticProcedure](https://schema.org/TherapeuticProcedure)
- [PhysicalExam](https://schema.org/PhysicalExam)

Thoughts on this proposal @gtsueng?  The line between medical guidance and protocols can get blurry (e.g. best practices on decontaminating face masks)
- keep Protocol as the master class; separate out into subcategories:
     - LabProtocol
     - AnalysisProtocol
     - MedicalProcedure
           - DiagnosticProcedure
           - TherapeuticProcedure
           - PhysicalExam
- create a MedicalGuideline class to encompass medical guidelines + public health policy guidelines (e.g. recommendations on what "essential businesses" are)

Not sure whether if we use this model we want LabProtocol, etc. to be formal subclasses of Protocol, or just add a `protocolType` category as a Property of Protocol.

**Comment by gtsueng** [comment]
I think having `protocolType` is the best way to go because in my head the ambiguous cases happen to be of two types making them ambiguous. To me, it makes sense to be just categorize an ambiguous protocol as being of two types, rather than forcing it into a sub-schema which may not be suitable for it.
