### ISSUE TITLE
Add all outbreak Classes to the Yaml file

### ISSUE THREAD

**Issue by kwende** [SuLab/outbreak.info-resources#34]
Format of the classes (such as outbreak classes), should be similar to; 

```
  # ---- DATASET ----
  - "@id":                 niaid:NiaidDataset
    "@type":               rdfs:Class
    rdfs:comment:          "A schema describing a minimal Dataset for the National Institute of Allergy and Infectious Disease (NIAID). A dataset is a collection of data of a particular experimental type. Additional schema.org and/or custom properties could be added."
    rdfs:label:            NiaidDataset
    rdfs:subClassOf:
      "@id":               schema:Dataset
    schema:isPartOf:
      "@id":               https://discovery.biothings.io/view/niaid/
```

**Comment by kwende** [comment]
from @flaneuse : 

``` The final schema will include 6 base Classes: Protocol, Publication, Analysis, Dataset, ClinicalTrial, Reagent + their associated properties, and some generic Classes that are reused like People , Organization, etc.```

**Comment by kwende** [comment]
[outbreak:ClinicalTrial, outbreak:Analysis, outbreak:Publication, outbreak:Dataset, outbreak:Protocol, outbreak:Person, outbreak:Organization, outbreak:Instrument, outbreak:StudyDesign, outbreak:ArmGroup, outbreak:Intervention, outbreak:Eligibility]

**Comment by kwende** [comment]
@gtsueng and @flaneuse : where are these defined currently? Or are these all ones I am responsible for defining? 

```[outbreak:ClinicalTrial, outbreak:Analysis, outbreak:Publication, outbreak:Dataset, outbreak:Protocol, outbreak:Person, outbreak:Organization, outbreak:Instrument, outbreak:StudyDesign, outbreak:ArmGroup, outbreak:Intervention, outbreak:Eligibility]```

I'm down for a talk soon if you want.

**Comment by gtsueng** [comment]
@kwende these should be available as tabs in the sheet now.

**Comment by kwende** [comment]
@gtsueng , thanks. Working on them now. I will have these done by tonight. 

Assuming we want @marcodarko I'm assuming the format needs to be similar to: 

```  - "@id":                 niaid:NiaidDataset
    "@type":               rdfs:Class
    rdfs:comment:          "A schema describing a minimal Dataset for the National Institute of Allergy and Infectious Disease (NIAID). A dataset is a collection of data of a particular experimental type. Additional schema.org and/or custom properties could be added."
    rdfs:label:            NiaidDataset
    rdfs:subClassOf:
      "@id":               schema:Dataset
    schema:isPartOf:
      "@id":               https://discovery.biothings.io/view/niaid/```
