### ISSUE TITLE
Include domainIncludes

### ISSUE THREAD

**Issue by kwende** [SuLab/outbreak.info-resources#35]
You’ll need to add an rdfs:Class for each schema type, as well as any objects within them.  You’ll also need to add
schema:domainIncludes: 
- "@id":         outbreak:Analysis

- '@id': author
  '@type': rdf:Property
  marginality: required
  owl:cardinality: many
  rdfs:comment: The name of the author as provided by the resource
  rdfs:subClassOf:
    '@id': https://schema.org/author
  schema:domainIncludes:
    - "@id":  outbreak:Analysis
  schema:rangeIncludes:
    - '@id': outbreak:Person
    - '@id': outbreak:Organization
​
- '@id': Person
  '@type': rdfs:Class
  rdfs:comment: A person
  rdfs:subClassOf:
    '@id': https://schema.org/person
  schema:isPartOf:
    "@id": https://outbreak.info/schema
​
- '@id': name
  '@type': rdf:Property
  marginality: required
  owl:cardinality: one
  rdfs:comment: The name of the person
  rdfs:subClassOf:
    '@id': https://schema.org/name
  schema:domainIncludes:
    - "@id":  outbreak:Person
  schema:rangeIncludes:
    - '@id': schema:Text

**Comment by kwende** [comment]
@gtsueng and @flaneuse : under what column is this defined in the spreadsheets?

**Comment by gtsueng** [comment]
originally just derived from the title of the sheet...added as 'domainIncludes' for each sheet
