### ISSUE TITLE
Verify schema on Data Discovery Engine

### ISSUE THREAD

**Issue by kwende** [SuLab/outbreak.info-resources#39]
use the Data Discovery Engine @marcocano et al. built to visualize and register the schema; make sure it all makes sense and allow others to extend off our schema. You can test this out at https://discovery.biothings.io/schema-playground and entering “https://raw.githubusercontent.com/SuLab/niaid-data-portal/master/schema/NIAIDDataset.json”

**Comment by gtsueng** [comment]
Note that we already have the name space registered for the schema.  Once this schema is working with the data discovery engine, it should either be appended/merged or replace the outbreak.json file.
