### ISSUE TITLE
Missing prs namespace in context

### ISSUE THREAD

**Issue by kwende** [SuLab/outbreak.info-resources#51]
prs:StartDateType, PrimaryCompletionDateType, StudyFirstPostDateType

@gtsueng or @marcodarko or @flaneuse, any idea what the URL is for this? I can't seem to find it.

**Comment by gtsueng** [comment]
The url for the schema is here: https://prsinfo.clinicaltrials.gov/ProtocolRecordSchema.xsd

But, I'm not sure it's in a format that's compatible with the DDE playground. @marcodarko can you check?
